### ISSUE TITLE
UV4L Raspidisp screen is garbled

### ISSUE THREAD

**Issue by chadwallacehart** [webrtcHacks/aiy_vision_web_server#5]
This appears to have happened after the June 25 UV4L update.

![image](https://user-images.githubusercontent.com/6531125/42121014-66a400b4-7bf3-11e8-8a1f-cf1845814ea6.png)

@julianoes and @siyer7881 reported this in #3 on the Pi Zero. It is happening for me on the Pi3.

I believe there might have been something in the June 25th update of UV4L causing this. I asked the UV4L author to take a look.

**Comment by lproj** [comment]
Hi, does upgrading the image or the firmware solve the problem?

**Comment by julianoes** [comment]
Ok, I did another upgrade and reboot, and now I get an error with the LED device:
```
python3 server.py --framerate 10 --hres 640 --vres 480
socket waiting for connection...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 118, in run_inference
    leds = Leds()
  File "/opt/aiy/projects-python/src/aiy/vision/leds.py", line 126, in __init__
    self.reset()
  File "/opt/aiy/projects-python/src/aiy/vision/leds.py", line 129, in reset
    _write(_device_file('reset'), 1)
  File "/opt/aiy/projects-python/src/aiy/vision/leds.py", line 37, in _write
    with open(path, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/leds/ktd202x:led1/device/reset
```
There is always something :smile: .

I was able to resolve that using the fix in https://github.com/google/aiyprojects-raspbian/issues/385#issuecomment-392231547.

I now get (even after checking all connections):
```
python3 server.py --framerate 10 --hres 640 --vres 480
socket waiting for connection...
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 91, in __init__
    self._dev = open(SPICOMM_DEV, 'r+b', 0)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 144, in run_inference
    with CameraInference(tf_model) as inference:
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 67, in __init__
    self._engine = InferenceEngine()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 164, in __init__
    self._transport = make_transport()
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 89, in make_transport
    return _SpiTransport()
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 29, in __init__
    self._spicomm = _spicomm.Spicomm()
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 93, in __init__
    raise SpicommDevNotFoundError
aiy._drivers._spicomm.SpicommDevNotFoundError
```

I ran `pintest` from wiringPi without anything connected and that was fine:
```
/pintest 
...
          The main 8 GPIO pins  0: 7:  OK
                The 5 SPI pins 10:14:  OK
               The serial pins 15:16:  OK
                  The I2C pins  8: 9:  OK

```

**Comment by chadwallacehart** [comment]
@julianoes I think you meant to do this:
`dmesg | grep aiy`

Mine doesn't show anything under `googlevisionbonnet`

It sounds like an issue with the AIY kit not updating that I would take up in the AIY repo. With @lproj's recent fix, it might be easier to just reflash the SD and start the AIY Vision Web Server install all over.

**Comment by julianoes** [comment]
Ok, so I replaced the vision bonnet and the SPI error remained the same. I then reflashed the SD card and the vision bonnet gets recognized again.

I tried the server and the annotation is now working properly, the stream is not garbled anymore but unfortunately the initial image freezes.

**Comment by siyer7881** [comment]
@chadwallacehart  I’m trying to output the joy score to an ifttt channel, so that we can get a notification every time the joy score is below a certain threshold. I tried modifying the output.json object to help me do that, but it hasn’t worked.

How will we make post calls to this webhook?
        # requests.post("https://maker.ifttt.com/trigger/MakeUseOf_Test/with/key/{secret_key}"

I’m kinda stuck and would love input on this
